"use strict";
exports.__esModule = true;
var mobile_1 = require("./mobile");
var mobilelibrary_1 = require("./mobilelibrary");
var nokia3210 = new mobile_1.Mobile("The Rock", "3210", "Nokia", 16, "Black", false, 0, 30);
var iPhone3G = new mobile_1.Mobile("The First", "iPhone3G", "Apple", 128, "White Pearl", false, 1, 60);
var samsungGalaxy10 = new mobile_1.Mobile("The Bomb", "Galaxy10", "Samsung", 256, "Blue", true, 4, 400);
var nokia3310 = new mobile_1.Mobile("The Best", "3310", "Nokia", 16, "Black", false, 0, 50);
var iphone8G = new mobile_1.Mobile("The First", "iPhone8G", "Apple", 256, "White Pearl", false, 1, 350);
var samsungGalaxyNote = new mobile_1.Mobile("The Note", "GalaxyNote", "Samsung", 256, "Blue", true, 3, 700);
var terminales = [nokia3310, iphone8G, samsungGalaxyNote];
var library = new mobilelibrary_1.MobileLibrary("Whatever", "Madrid", terminales);
// console.log(library.totalPriceCalculation());
// console.log("-------------");
// Probar que funcionan los métodos del objeto.
console.log(library.getLocation());
console.log("-------------");
console.log(library.getMobiles());
console.log("-------------");
console.log(library.getName());
console.log("-------------");
library.setLocation("una nueva location");
console.log(library.getLocation());
console.log("-------------");
library.setName("un nuevo nombre");
console.log(library.getName());
console.log("-------------");
library.setMobiles(terminales);
console.log(library.getMobiles());
console.log("-------------");
// probar printLibrary.
console.log(library.printLibrary());
console.log("-------------");
console.log(library.gettotalPriceCalculation());
console.log("-------------");
console.log(library.getMobiles());
console.log("-------------");
console.log(library.getName());
